### ISSUE TITLE
Store hash(key) => value in the DB to reduce I/O operations for reads

### ISSUE THREAD

**Issue by musalbas** [celestiaorg/smt#14]

**Comment by adlerjohn** [comment]
This should probably be `index in tree -> value` (and for leaves only) instead of `hash(index in tree) -> value`. The reason is that there could be specific entries in the state that are at specific locations, [e.g.](https://github.com/lazyledger/lazyledger-specs/blob/cd66b26de30eeb2ef88209f0536e6571937de52a/specs/data_structures.md#activevalidatorcount). Hashing or not should be decided at the application side rather than required by the SMT.

**Comment by liamsi** [comment]
referencing #8

**Comment by tzdybal** [comment]
For now, SMT cannot be iterated (except iterating underlying map-store if possible, but it's a hack). 
If iteration is not necessary, I can't see a difference between `hash(key)->value` and `key->value` mapping (except hashing footprint).
Currently, there is only `hash(value)->value` mapping, which has one additional feature: de-duplication of values. On the other hand, it complicates removal of orphans (because we can't remove `hash(value)` from mapstore without storing reference count for values somewhere.

**Comment by adlerjohn** [comment]
Deduplication at the cost of having to reference count is probably not a good property to have. How many accounts are going to have _exactly_ the same balance and nonce, etc.

**Comment by tzdybal** [comment]
Traversing the tree to access the data, cryptographically ensures that value is actually present/absent in the tree. 

Accessing by key, means that you can't actually trust values from the tree (for example after `ImportSparseMerkleTree` call), because map store can be modified, without "invalidating" root ("dangling" values can be added, values can be changed).
After traversing a tree user can be sure that value corresponds to the root. Without it user has to prove it.

Another issue is the lack of "history". In current implementation, you can use old root to access old value for a key. After optimization, only latest version of the value will be returned.

Maybe we should use a bit more sophisticated form of mapping like: `root+key->value`? This will enable efficient access to previous versions of keys, and as you said, lack of de-duplication of values is not a big issue.
